// Code generated by mockery v2.14.0. DO NOT EDIT.

package log

import mock "github.com/stretchr/testify/mock"

// mockExitFunc is an autogenerated mock type for the exitFunc type
type mockExitFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *mockExitFunc) Execute(_a0 int) {
	_m.Called(_a0)
}

type mockConstructorTestingTnewMockExitFunc interface {
	mock.TestingT
	Cleanup(func())
}

// newMockExitFunc creates a new instance of mockExitFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockExitFunc(t mockConstructorTestingTnewMockExitFunc) *mockExitFunc {
	mock := &mockExitFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
